# Be sure to have direnv allow the .envrc file before running this
#   OR load the variables from .envrc yourself

# yaml-language-server: $schema=https://taskfile.dev/schema.json

# 
# (see build/README.md)
# 

version: '3'

includes:
  winbuild: ./build/win/_tasks.yml
  macbuild: ./build/mac/_tasks.yml
  gnubuild: ./build/gnu/_tasks.yml

tasks:
  check_env:
    cmds:
      - echo $PROJECT_DIR
      - echo $SOURCE_DIR
      - echo "Unix timestamp {{now | unixEpoch}}"

  # Top level aliases for convenience

  rear-winbuid:
    aliases: [rear-win]
    cmds:
      - task: winbuild:rear-x64


  rear-macbuid:
    aliases: [rear-mac]
    cmds:
      - task: macbuild:rear-intel

  rear-macasbuid:
    aliases: [rear-macas]
    cmds:
      - task: macbuild:rear-apple


  rear-gnubuid:
    aliases: [rear-gnu]
    cmds:
      - task: gnubuild:rear-x64


  # Linting

  lint:
    desc: A task to check the main(webdevn) module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn.nim

  lint-cli:
    desc: A task to check the cli module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/cli.nim

  lint-localserver:
    desc: A task to check the localserver module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/localserver.nim

  lint-scribe:
    desc: A task to check the loggo module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/scribe.nim

  lint-typeds:
    desc: A task to check the type_defs module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/type_defs.nim

  lint-utils:
    desc: A task to check the utils module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/utils.nim

  # Testing

  test-cli:
    desc: Run spec for cli suite
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/cli_spec.nim "Cli_BS::"

  test-utils:
    desc: Run spec for util suite
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/utils_spec.nim "Utils_BS::"

  test-scribe:
    desc: Run spec for scribe suite
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/scribe_spec.nim "Scribe_BS::"
