# Be sure to have direnv allow the .envrc file before running this
#   OR load the variables from .envrc yourself

# yaml-language-server: $schema=https://taskfile.dev/schema.json


version: '3'

includes:
  winbuild: ./build/win/_tasks.yml
  macbuild: ./build/mac/_tasks.yml
  gnubuild: ./build/gnu/_tasks.yml

vars:
  NIMBLEPKGDEPSVER:
    # Ensure the dev only dependencies are excluded here
    sh: jq -r '[.packages | to_entries[] | select(.key | IN("checksums") | not) | "\(.key)@\(.value.version)"] | join(", ")' nimble.lock
  NIMDEFINE_VER:
    "-d:webdevnVersion={{.VERSION_NUM}}"
  NIMDEFINE_DEPVERS:
    "-d:webdevnDependencyVersions={{.NIMBLEPKGDEPSVER}}"
  NIMDEFINEFLAGS:
    "{{.NIMDEFINE_VER}} {{.NIMDEFINE_DEPVERS}}"

tasks:
  check_env:
    silent: true
    cmds:
      - 'echo version: $VERSION_NUM'
      - 'echo version for nimble $SEMANTIC_VERSION'
      - 'echo project in: $PROJECT_DIR'
      - 'echo source files: $SOURCE_DIR'
      - 'echo nimble package deps: {{.NIMBLEPKGDEPSVER}}'
      - 'echo nim define flags: {{.NIMDEFINEFLAGS}}'
      - 'echo Unix timestamp: {{now | unixEpoch}}'


  # Package Mangement

  update-nimble-pkgver:
    aliases: [update-saniv]
    desc: Sync version number in .nimble file with environment variable as nimble requires variable to be string literal
    cmds:
      - sed -i 's/^version *= *".*"/version = "{{.SEMANTIC_VERSION}}"/' webdevn.nimble

  verify_app_meta_version:
    aliases: [metavers]
    desc: Get a readout of the version as read by the app
    cmds:
      - nim r --hints:off {{.NIMDEFINEFLAGS}} $SOURCE_DIR/webdevn.nim -V

  check-app-help:
    aliases: [chelp]
    desc: Print the help message
    cmds:
      - nim r --hints:off {{.NIMDEFINEFLAGS}} $SOURCE_DIR/webdevn.nim -h


  # Running

  run_project:
    aliases: [runit]
    desc: Compiles and executes code with cli args (after '--')
    cmds:
      - nim r $SOURCE_DIR/webdevn.nim {{.CLI_ARGS}}


  # Top level aliases for convenience

  rear-winbuild:
    aliases: [rear-win]
    cmds:
      - task: winbuild:rear-x64

  wrap-winbuild:
    aliases: [wrap-win]
    cmds:
      - task: winbuild:wrap-x64

  sweep-winbuild:
    aliases: [sweep-win]
    cmds:
      - task: winbuild:sweep-x64


  rear-macdabuild:
    aliases: [rear-mac]
    cmds:
      - task: macbuild:rear-darwinx64

  wrap-macdabuild:
    aliases: [wrap-mac]
    cmds:
      - task: macbuild:wrap-darwinx64

  sweep-macdabuild:
    aliases: [sweep-mac]
    cmds:
      - task: macbuild:sweep-darwin

  rear-macasbuild:
    aliases: [rear-macas]
    cmds:
      - task: macbuild:rear-darwinarm64


  rear-gnubuild:
    aliases: [rear-gnu]
    cmds:
      - task: gnubuild:rear-x64

  wrap-gnubuild:
    aliases: [wrap-gnu]
    cmds:
      - task: gnubuild:wrap-x64

  sweep-gnubuild:
    aliases: [sweep-gnu]
    cmds:
      - task: gnubuild:sweep-x64


  # Linting

  lint:
    desc: A task to check the main(webdevn) module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn.nim

  lint-cli:
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/cli.nim

  lint-localserver:
    aliases: [lint-loser]
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/localserver.nim

  lint-scribe:
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/scribe.nim

  lint-typedefs:
    aliases: [lint-typeds]
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/type_defs.nim

  lint-utils:
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/utils.nim


  # Testing

  # Can also run separate test tasks in parallel with -p flag
  test-behavior-shape:
    aliases: [all-bs]
    desc: Run all behavior and shape suites
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/all_bs_spec.nim

  test-cli:
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/cli_spec.nim "Cli_BS::"

  test-utils:
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/utils_spec.nim "Utils_BS::"

  test-scribe:
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/scribe_spec.nim "Scribe_BS::"

  test-localserver:
    aliases: [test-loser]
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/localserver_spec.nim "LocalServer_BS::"
