# Be sure to have direnv allow the .envrc file before running this
#   OR load the variables from .envrc yourself

# yaml-language-server: $schema=https://taskfile.dev/schema.json

# 
# (see build/README.md)
# 

version: '3'

includes:
  winbuild: ./build/win/_tasks.yml
  macbuild: ./build/mac/_tasks.yml
  gnubuild: ./build/gnu/_tasks.yml

vars:
  NIMBLEPKGDEPSVER:
    # Ensure the dev only dependencies are excluded here
    sh: jq -r '[.packages | to_entries[] | select(.key | IN("checksums") | not) | "\(.key)@\(.value.version)"] | join(", ")' nimble.lock

tasks:
  check_env:
    silent: true
    cmds:
      - 'echo version: $VERSION_NUM'
      - 'echo version for nimble $VERSION_FOR_NIMBLE'
      - 'echo project in: $PROJECT_DIR'
      - 'echo source files: $SOURCE_DIR'
      - 'echo nimble package deps: {{.NIMBLEPKGDEPSVER}}'
      - 'echo Unix timestamp: {{now | unixEpoch}}'


  # Package Mangement

  update-nimble-pkgver:
    aliases: [update-saniv]
    desc: Sync version number in .nimble file with environment variable as nimble requires variable to be string literal
    cmds:
      - sed -i 's/^version *= *".*"/version = "{{.VERSION_FOR_NIMBLE}}"/' webdevn.nimble


  # Running
  run_project:
    aliases: [runit]
    desc: Compiles and executes code with cli args (after '--')
    cmds:
      - nim r $SOURCE_DIR/webdevn.nim {{.CLI_ARGS}}


  # Top level aliases for convenience

  rear-winbuid:
    aliases: [rear-win]
    cmds:
      - task: winbuild:rear-x64

  wrap-winbuild:
    aliases: [wrap-win]
    cmds:
      - task: winbuild:wrap-x64

  sweep-winbuild:
    aliases: [sweep-win]
    cmds:
      - task: winbuild:sweep-x64


  rear-macbuid:
    aliases: [rear-mac]
    cmds:
      - task: macbuild:rear-intel

  rear-macasbuid:
    aliases: [rear-macas]
    cmds:
      - task: macbuild:rear-apple


  rear-gnubuid:
    aliases: [rear-gnu]
    cmds:
      - task: gnubuild:rear-x64


  # Linting

  lint:
    desc: A task to check the main(webdevn) module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn.nim

  lint-cli:
    desc: A task to check the cli module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/cli.nim

  lint-localserver:
    aliases: [lint-loser]
    desc: A task to check the localserver module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/localserver.nim

  lint-scribe:
    desc: A task to check the loggo module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/scribe.nim

  lint-typedefs:
    aliases: [lint-typeds]
    desc: A task to check the type_defs module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/type_defs.nim

  lint-utils:
    desc: A task to check the utils module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn/utils.nim


  # Testing

  # Can also run separate test tasks in parallel with -p flag
  test-behavior-shape:
    aliases: [all-bs]
    desc: Run all behavior and shape suites
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/all_bs_spec.nim

  test-cli:
    desc: Run spec for cli suite
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/cli_spec.nim "Cli_BS::"

  test-utils:
    desc: Run spec for util suite
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/utils_spec.nim "Utils_BS::"

  test-scribe:
    desc: Run spec for scribe suite
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/scribe_spec.nim "Scribe_BS::"

  test-localserver:
    aliases: [test-loser]
    desc: Run spec for localserver suite
    cmds:
      - nim r --hints:off {{.TEST_DIR}}/bs/localserver_spec.nim "LocalServer_BS::"
