# Be sure to have direnv allow the .envrc file before running this
#   OR load the variables from .envrc yourself

# yaml-language-server: $schema=https://taskfile.dev/schema.json


version: '3'

includes:
  build: ./build/_tasks.yml
  specs: ./spec/_tasks.yml

vars:
  NIMDEFINE_VER:
    "-d:appVersion={{.VERSION_NUM}}"
  NIMDEFINE_DEPVERS:
    "-d:appDepVersions={{.NIMBLEPKGDEPSVER}}"
  NIMDEFINEFLAGS:
    "{{.NIMDEFINE_VER}} {{.NIMDEFINE_DEPVERS}}"

tasks:
  check_env:
    silent: true
    cmds:
      - 'echo version: $VERSION_NUM'
      - 'echo version for nimble $SEMANTIC_VERSION'
      - 'echo project in: $PROJECT_DIR'
      - 'echo source files: $SOURCE_DIR'
      - 'echo nimble package deps: {{.NIMBLEPKGDEPSVER}}'
      - 'echo nim define flags: {{.NIMDEFINEFLAGS}}'
      - 'echo Unix timestamp: {{now | unixEpoch}}'


  # Package Mangement

  update-nimble-pkgver:
    aliases: [update-saniv]
    desc: Sync version number in .nimble file with environment variable as nimble requires variable to be string literal
    cmds:
      - sed -i 's/^version *= *".*"/version = "{{.SEMANTIC_VERSION}}"/' webdevn.nimble

  verify_app_meta_version:
    aliases: [metavers]
    desc: Get a readout of the version as read by the app
    cmds:
      - nim r --hints:off {{.NIMDEFINEFLAGS}} $SOURCE_DIR/webdevn.nim -V

  check-app-help:
    aliases: [chelp]
    desc: Print the help message
    cmds:
      - nim r --hints:off {{.NIMDEFINEFLAGS}} $SOURCE_DIR/webdevn.nim -h


  # Running

  run_project:
    aliases: [runit]
    desc: Compiles and executes code with cli args (after '--')
    cmds:
      - nim r $SOURCE_DIR/webdevn.nim {{.CLI_ARGS}}


  # Linting

  lint:
    desc: A task to check the main(webdevn) module for compile errors
    cmds:
      - nim check {{.SOURCE_DIR}}/webdevn.nim

  lint-cli:
    cmds:
      - nim check {{.SUBMODULE_DIR}}/cli.nim

  lint-localserver:
    aliases: [lint-loser]
    cmds:
      - nim check {{.SUBMODULE_DIR}}/localserver.nim

  lint-scribe:
    cmds:
      - nim check {{.SUBMODULE_DIR}}/scribe.nim

  lint-typedefs:
    aliases: [lint-typeds]
    cmds:
      - nim check {{.SUBMODULE_DIR}}/type_defs.nim

  lint-utils:
    cmds:
      - nim check {{.SUBMODULE_DIR}}/utils.nim
  
  lint-meta:
    cmds:
      - nim check {{.SUBMODULE_DIR}}/meta.nim
